// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"time"
)

type Migration struct {
	MigrationNumber int64     `json:"migration_number"`
	MigrationName   string    `json:"migration_name"`
	ExecutedAt      time.Time `json:"executed_at"`
}

type RsyncHistory struct {
	ID          int64      `json:"id"`
	Source      string     `json:"source"`
	Destination string     `json:"destination"`
	Options     string     `json:"options"`
	FullCommand string     `json:"full_command"`
	Status      string     `json:"status"`
	ExitCode    *int64     `json:"exit_code"`
	Output      *string    `json:"output"`
	StartedAt   *time.Time `json:"started_at"`
	CompletedAt *time.Time `json:"completed_at"`
	CreatedAt   time.Time  `json:"created_at"`
}
