// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rsync.sql

package dbgen

import (
	"context"
	"time"
)

const clearAllHistory = `-- name: ClearAllHistory :exec
DELETE FROM rsync_history
`

func (q *Queries) ClearAllHistory(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearAllHistory)
	return err
}

const createRsyncHistory = `-- name: CreateRsyncHistory :one
INSERT INTO rsync_history (source, destination, options, full_command, status)
VALUES (?, ?, ?, ?, 'pending')
RETURNING id, source, destination, options, full_command, status, exit_code, output, started_at, completed_at, created_at
`

type CreateRsyncHistoryParams struct {
	Source      string `json:"source"`
	Destination string `json:"destination"`
	Options     string `json:"options"`
	FullCommand string `json:"full_command"`
}

func (q *Queries) CreateRsyncHistory(ctx context.Context, arg CreateRsyncHistoryParams) (RsyncHistory, error) {
	row := q.db.QueryRowContext(ctx, createRsyncHistory,
		arg.Source,
		arg.Destination,
		arg.Options,
		arg.FullCommand,
	)
	var i RsyncHistory
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.Destination,
		&i.Options,
		&i.FullCommand,
		&i.Status,
		&i.ExitCode,
		&i.Output,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRsyncHistory = `-- name: DeleteRsyncHistory :exec
DELETE FROM rsync_history WHERE id = ?
`

func (q *Queries) DeleteRsyncHistory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRsyncHistory, id)
	return err
}

const getRsyncHistory = `-- name: GetRsyncHistory :one
SELECT id, source, destination, options, full_command, status, exit_code, output, started_at, completed_at, created_at FROM rsync_history WHERE id = ?
`

func (q *Queries) GetRsyncHistory(ctx context.Context, id int64) (RsyncHistory, error) {
	row := q.db.QueryRowContext(ctx, getRsyncHistory, id)
	var i RsyncHistory
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.Destination,
		&i.Options,
		&i.FullCommand,
		&i.Status,
		&i.ExitCode,
		&i.Output,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listRsyncHistory = `-- name: ListRsyncHistory :many
SELECT id, source, destination, options, full_command, status, exit_code, output, started_at, completed_at, created_at FROM rsync_history ORDER BY created_at DESC LIMIT ?
`

func (q *Queries) ListRsyncHistory(ctx context.Context, limit int64) ([]RsyncHistory, error) {
	rows, err := q.db.QueryContext(ctx, listRsyncHistory, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RsyncHistory{}
	for rows.Next() {
		var i RsyncHistory
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.Destination,
			&i.Options,
			&i.FullCommand,
			&i.Status,
			&i.ExitCode,
			&i.Output,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRsyncRunning = `-- name: UpdateRsyncRunning :exec
UPDATE rsync_history SET status = 'running', started_at = ? WHERE id = ?
`

type UpdateRsyncRunningParams struct {
	StartedAt *time.Time `json:"started_at"`
	ID        int64      `json:"id"`
}

func (q *Queries) UpdateRsyncRunning(ctx context.Context, arg UpdateRsyncRunningParams) error {
	_, err := q.db.ExecContext(ctx, updateRsyncRunning, arg.StartedAt, arg.ID)
	return err
}

const updateRsyncStatus = `-- name: UpdateRsyncStatus :exec
UPDATE rsync_history 
SET status = ?, exit_code = ?, output = ?, started_at = ?, completed_at = ?
WHERE id = ?
`

type UpdateRsyncStatusParams struct {
	Status      string     `json:"status"`
	ExitCode    *int64     `json:"exit_code"`
	Output      *string    `json:"output"`
	StartedAt   *time.Time `json:"started_at"`
	CompletedAt *time.Time `json:"completed_at"`
	ID          int64      `json:"id"`
}

func (q *Queries) UpdateRsyncStatus(ctx context.Context, arg UpdateRsyncStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateRsyncStatus,
		arg.Status,
		arg.ExitCode,
		arg.Output,
		arg.StartedAt,
		arg.CompletedAt,
		arg.ID,
	)
	return err
}
